Flask_views_restructured/myproject/models.py
from myproject import db
# Models


class Puppy(db.Model):

    __tablename__ = 'puppies'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    # one to one relationship
    owner = db.relationship('Owner', backref='puppy', uselist=False)

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        if self.owner:
            return f"Puppy name: {self.name} has owner: {self.owner.name}"
        return f"Puppy name: {self.name}"


class Owner(db.Model):
    __tablename__ = 'owners'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    puppy_id = db.Column(db.Integer, db.ForeignKey('puppies.id'))

    def __init__(self, name, puppy_id):
        self.name = name
        self.puppy_id = puppy_id

    def __repr__(self):
        return f"Owner name: {self.name}"

Flask_views_restructured/myproject/owners/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, StringField
from wtforms.fields.simple import SubmitField


class AddOwner(FlaskForm):
    name = StringField('Name of Owner')
    puppyId = IntegerField('Id of Puppy')
    submit = SubmitField('Add Owner')

Flask_views_restructured/myproject/puppies/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, StringField
from wtforms.fields.simple import SubmitField


class AddForm(FlaskForm):
    name = StringField('Name of Puppy')
    submit = SubmitField('Add Puppy')


class DelForm(FlaskForm):
    id = IntegerField("Id Number of Puppy to Remove: ")
    submit = SubmitField("Remove Puppy")

Flask_views_restructured/myproject/__init__.py
# set up db inside the __init__.py under myproject folder



import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate


app = Flask(__name__)

app.config['SECRET_KEY'] = 'mysecretkey'

basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + \
    os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False


db = SQLAlchemy(app)

Migrate(app, db)
from myproject.puppies.views import puppies_blueprint
from myproject.owners.views import owners_blueprint
app.register_blueprint(puppies_blueprint, url_prefix='/puppies')
app.register_blueprint(owners_blueprint, url_prefix='/owners')

Flask_views_restructured/myproject/owners/views.py
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.models import Owner
from myproject.owners.forms import AddOwner


owners_blueprint = Blueprint(
    'owners', __name__, template_folder='templates/owners')


@owners_blueprint.route('/add', methods=['GET', 'POST'])
def add():

    form = AddOwner()

    if form.validate_on_submit():
        # grab details from the form
        name = form.name.data
        puppyId = form.puppyId.data

        # Create an owner instance
        owner = Owner(name, puppyId)

        db.session.add(owner)
        db.session.commit()

        return redirect(url_for('puppies.list'))

    return render_template('owner.html', form=form)

Flask_views_restructured/myproject/puppies/views.py
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.models import Puppy
from myproject.puppies.forms import AddForm, DelForm


puppies_blueprint = Blueprint(
    'puppies', __name__, template_folder='templates/puppies')


@puppies_blueprint.route('/add', methods=['GET', 'POST'])
def add_pup():

    form = AddForm()

    if form.validate_on_submit():

        name = form.name.data
        new_pup = Puppy(name)
        db.session.add(new_pup)
        db.session.commit()

        return redirect(url_for('puppies.list'))

    return render_template('add.html', form=form)


@puppies_blueprint.route('/list')
def list():
    puppies = Puppy.query.all()
    return render_template('list.html', puppies=puppies)


@puppies_blueprint.route('/delete', methods=['GET', 'POST'])
def del_pup():

    form = DelForm()

    if form.validate_on_submit():

        id = form.id.data
        pup = Puppy.query.get(id)
        db.session.delete(pup)
        db.session.commit()

        return redirect(url_for('puppies.list'))

    return render_template('delete.html', form=form)

Flask_views_restructured/myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>


    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>


</head>

<body>

    <nav class='navbar navbar-expand-lg navbar-light bg-light'>
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{{url_for('index')}}">Home</a>
            <a class="nav-item nav-link" href="{{url_for('puppies.add_pup')}}">Add Pup</a>
            <a class="nav-item nav-link" href="{{url_for('puppies.list')}}">List of Pups</a>
            <a class="nav-item nav-link" href="{{url_for('puppies.del_pup')}}">Delete Pup</a>
            <a class="nav-item nav-link" href="{{url_for('owners.add')}}">Add Owner</a>

        </div>
    </nav>
    {% block content %}


    {% endblock %}





</body>

</html>

Flask_views_restructured/myproject/templates/home.html
{% extends "base.html" %}


{% block content %}

<div class="jumbotron">
    <h1>Welcome</h1>
</div>



{% endblock %}